name: EtriaUtils
version: v1.0
main: com.etriacraft.EtriaUtils.EtriaUtils
commands:
permissions:
  eu.dropsave:
    description: Saves item drops on death.
  eu.saveexp:
    description: Saves EXP on death.