name: EtriaUtils
version: v1.1
main: com.etriacraft.EtriaUtils.EtriaUtils
commands:
  modchat:
    description: Modchat command
    usage: /<command> [message]
    aliases: [ac, mc, mb, modbroadcast]
  list:
    description: Shows a player list
    usage: /<command>
    aliases: [who, list, online, players]
permissions:
  eu.dropsave:
    description: Saves item drops on death.
  eu.saveexp:
    description: Saves EXP on death.
  eu.chat.modchat:
    description: See / Use modchat